version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: leaderboard-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: m1_s3cr3t
      MARIADB_DATABASE: leaderboard
      MARIADB_USER: root
      MARIADB_PASSWORD: m1_s3cr3t
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
